from datetime import timedelta

# Fixed constants from design document
AIRPORT = "LHR"
HUB = "AMS"
FLIGHTS_PER_DAY = 120
TRANSFER_RATIO = 0.30
TRANSFER_P90_MINUTES = 35
BUFFER_MINUTES = 10
PASSENGERS_MEAN = 160
PASSENGERS_STD = 30
PASSENGERS_MIN = 80
PASSENGERS_MAX = 240
BAG_COUNT_WEIGHTS = [0.15, 0.55, 0.25, 0.05]
OUT_OF_ORDER_RATE = 0.05
OUT_OF_ORDER_MIN_DELAY = timedelta(minutes=2)
OUT_OF_ORDER_MAX_DELAY = timedelta(minutes=6)
DEFAULT_BAG_CUTOFF_OFFSET = timedelta(minutes=40)

# Event timing distributions (minutes)
CHECKED_IN_MEAN = 120
CHECKED_IN_STD = 30
CHECKED_IN_MIN = 60
CHECKED_IN_MAX = 240
INDUCTED_P50 = 5
INDUCTED_P90 = 15
SCREENED_P50 = 3
SCREENED_P90 = 10
MAKEUP_P50 = 10
MAKEUP_P90 = 25
LOADED_BUFFER_MINUTES = 5

# Destinations used for synthetic schedules
PRIMARY_DESTINATIONS = ["AMS", "CDG", "FRA", "JFK", "DXB", "DOH", "SFO", "LAX", "SIN", "MAD"]
CONNECTION_DESTINATIONS = ["FRA", "MUC", "MAD", "LIS", "ZRH", "ARN", "BCN", "FCO", "ATH", "JFK"]
